server:
  port: 9000
logger:
  filename: storage/log/logs.log
  max_size: 90000
  max_backup: 10
  max_age: 90000
  compress: false
  log_type: daily
  level: debug
aws:
  region: xxx
  access_key: xxx
  secret_key: xxx
  sqs:
    queue_name: email-box
    timeout: 30
database:
  driver: sqlite
  sqlite_file_path: web3_blog.db
business:
  support_email: support@zou8944.com
arweave:
  wallet_key_file: ./keyfile.json
  endpoint: https://arseed.web3infra.dev
  bundlr_endpoint: "https://node2.bundlr.network"
  app_name: "4tune-web3-blog"
jwt:
  sign_key: xxxx