server:
  port: 9000
logger:
  filename: storage/log/logs.log
  max_size: 90000
  max_backup: 10
  max_age: 90000
  compress: false
  log_type: daily
  level: debug
aws:
  region: xxx
  access_key: xxx
  secret_key: xxx
  sqs:
    queue_name: email-box
    timeout: 30
database:
  driver: sqlite
  sqlite_file_path: web3_blog.db
business:
  support_email: support@zou8944.com
web3_storage_token: xxx
jwt:
  sign_key: xxxx